[book]
title = "Stylix"
language = "en"

[preprocessor.alerts]

[output.html]
site-url = "/stylix/"
git-repository-url = "https://github.com/danth/stylix"
edit-url-template = "https://github.com/danth/stylix/edit/master/docs/{path}"
no-section-label = true

[output.html.fold]
enable = true
