name: Check

on:
  push:

permissions:
  contents: read

jobs:
  get-derivations:
    runs-on: ubuntu-24.04

    steps:
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - id: get-derivations
        run: |
          nix flake show github:${{ github.repository }}/${{ github.event.pull_request.head.sha || github.sha }} --json | jq -rc 'to_entries | map(.key as $type | select($type == "checks" or $type == "packages") | .value | to_entries | map(.key as $arch | select($arch == "x86_64-linux" or $arch == "x86_64-darwin") | .value | to_entries | map({type: $type, arch: $arch, os: (if $arch == "x86_64-linux" then "ubuntu-24.04" else "macos-14" end), key: .key})) | flatten) | flatten | "derivations=\(.)"' >> $GITHUB_OUTPUT

    outputs:
      derivations: ${{ steps.get-derivations.outputs.derivations }}

  check:
    runs-on: ${{ matrix.check.os }}

    name: ${{ matrix.check.key }} on ${{ matrix.check.arch }}
    needs: get-derivations

    strategy:
      fail-fast: false
      matrix:
        check: ${{ fromJSON(needs.get-derivations.outputs.derivations) }}

    steps:
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix -L check github:${{ github.repository }}/${{ github.event.pull_request.head.sha || github.sha }}#${{ matrix.check.type }}.${{ matrix.check.arch }}.${{ matrix.check.key }} --no-update-lock-file
